const mongoose = require("mongoose");
const Product = require("./models/productModel");
require("dotenv").config();

mongoose.connect(process.env.MONGO_URI).then(async () => {
  try {
    // clear old products
    await Product.deleteMany();

    //insert new products
    await Product.insertMany([
      {
        id: 1,
        name: "Nike Air Max",
        price: 2200,
        category: "Shoes",
        ratingP: 4.9,
        image: "nike-air-max.png",
        images: ["nike-air-max.png", "barcode.avif"],
        featured: true,
        discount: 30,
      },
      {
        id: 2,
        name: "Potatoes",
        category: "Vegetables & Fruits",
        quantity: 89,
        price: 19,
        image: "potato.jpg",
        images: ["potato.jpg", "barcode.avif", "fssai.jpg"],
        ratingP: 4.1,
        description: "product description",
        vendor: "Daily Fresh Farms, Harayana",
      },
      {
        id: 3,
        name: "Mix Fruit Juice",
        price: 120,
        category: "Drinks",
        ratingP: 4.9,
        image: "mix-fruit-juice.png",
        images: ["mix-fruit-juice.png", "barcode.avif"],
        featured: true,
        discount: 5,
      },
      {
        id: 4,
        name: "Water Bottle 1L",
        price: 80,
        category: "Kitchen",
        ratingP: 4.8,
        image: "water-bottle.png",
        images: ["water-bottle.png", "barcode.avif"],
        featured: true,
        discount: 22,
      },
      {
        id: 5,
        name: "Peach",
        category: "Vegetables & Fruits",
        quantity: 22,
        price: 79,
        image: "peach.avif",
        images: ["peach.avif", "barcode.avif", "fssai.jpg"],
        ratingP: 4.2,
        description: "product description",
        vendor: "Daily Fresh Farms, Harayana",
      },
      {
        id: 6,
        name: "Britannia Cake",
        category: "Cake & Milk",
        quantity: 29,
        price: 79,
        image: "britanniacake.webp",
        images: ["britanniacake.webp", "barcode.avif", "fssai.jpg"],
        ratingP: 3.9,
        description: "product description",
        vendor: "A1 Bakeries, Delhi",
      },
      {
        id: 7,
        name: "Ice Tea",
        category: "Coffee & Tea",
        quantity: 15,
        price: 39,
        image: "icetea.webp",
        images: ["icetea.webp", "barcode.avif", "fssai.jpg"],
        ratingP: 3.7,
        description: "product description",
        vendor: "Tea Valley, Assam",
      },
      {
        id: 8,
        name: "Orange",
        category: "Vegetables & Fruits",
        quantity: 39,
        price: 89,
        image: "orange.jpg",
        images: ["orange.jpg", "barcode.avif", "fssai.jpg"],
        ratingP: 4.1,
        description: "product description",
        vendor: "Daily Fresh Farms, Harayana",
        discount: 12,
      },
      {
        id: 9,
        name: "Buffalo Milk",
        category: "Cake & Milk",
        quantity: 49,
        price: 99,
        image: "buffalomilk.jpg",
        images: ["buffalomilk.jpg", "barcode.avif", "fssai.jpg"],
        ratingP: 4.3,
        description: "product description",
        vendor: "D",
      },
      {
        id: 10,
        name: "Cow Milk",
        category: "Cake & Milk",
        quantity: 23,
        price: 79,
        image: "cowmilk.webp",
        images: ["cowmilk.webp", "barcode.avif", "fssai.jpg"],
        ratingP: 4.8,
        description: "product description",
        vendor: "D",
        discount: 5,
      },
      {
        id: 11,
        name: "Cat Food",
        category: "Pet Food",
        quantity: 9,
        price: 399,
        image: "catfood.webp",
        images: ["catfood.webp", "barcode.avif", "fssai.jpg"],
        ratingP: 3.4,
        description: "product description",
        vendor: "Pet Foods India, Gujarat",
      },
      {
        id: 12,
        name: "Dog Food",
        category: "Pet Food",
        quantity: 18,
        price: 499,
        image: "dogfood.webp",
        images: ["dogfood.webp", "barcode.avif", "fssai.jpg"],
        ratingP: 3.8,
        description: "product description",
        vendor: "Pet Foods India, Gujarat",
      },
      {
        id: 13,
        name: "Samsung S25",
        price: 60000,
        category: "Electronics",
        ratingP: 4.8,
        image: "samsung-s25.png",
        images: ["samsung-s25.png", "barcode.avif"],
        featured: true,
        discount: 15,
      },
      {
        id: 14,
        name: "Brown Tea",
        category: "Coffee & Tea",
        quantity: 4,
        price: 25,
        image: "browntea.webp",
        images: ["browntea.webp", "barcode.avif", "fssai.jpg"],
        ratingP: 4.5,
        description: "product description",
        vendor: "Tea Valley, Assam",
      },
      {
        id: 15,
        name: "Nescafe Coffee",
        category: "Coffee & Tea",
        quantity: 31,
        price: 10,
        image: "nescafecoffee.jpeg",
        images: ["nescafecoffee.jpeg", "barcode.avif", "fssai.jpg"],
        ratingP: 4.4,
        description: "product description",
        vendor: "Tea Valley, Assam",
      },
      {
        id: 16,
        name: "Spinach",
        category: "Vegetables & Fruits",
        quantity: 14,
        price: 49,
        image: "spinach.jpg",
        images: ["spinach.jpg", "barcode.avif", "fssai.jpg"],
        ratingP: 4.1,
        description: "product description",
        vendor: "Daily Fresh Farms, Harayana",
        discount: 10,
      },
      {
        id: 17,
        name: "Organic Kiwi",
        category: "Vegetables & Fruits",
        quantity: 8,
        price: 49,
        image: "kiwi.webp",
        images: ["kiwi.webp", "kiwi.webp", "barcode.avif", "fssai.jpg"],
        ratingP: 4.4,
        description: "product description",
        vendor: "Daily Fresh Farms, Harayana",
      },
      {
        id: 18,
        name: "Chocolate Cake",
        category: "Cake & Milk",
        quantity: 15,
        price: 299,
        image: "chocolatecake.jpg",
        images: ["chocolatecake.jpg", "barcode.avif", "fssai.jpg"],
        ratingP: 4.8,
        description:
          "A chocolate cake is a rich, moist dessert made with chocolate or cocoa powder, flour, and sugar, often featuring layers of cake and cream.",
        vendor: "A1 Bakeries, Delhi",
        addInfo: "Its good",
      },
      {
        id: 19,
        name: "Wired Earphones",
        category: "Electronics",
        quantity: 5,
        price: 2499,
        image: "earphone4.jpg",
        images: ["earphone1.webp", "earphone2.webp", "earphone3.jpg", "earphone4.jpg"],
        ratingP: 4.4,
        description:
          "The Apple Earphones are wired earphones designed for convenience and style. They boast 9.0mm bass drivers for enhanced audio, delivering rich, deep bass tones. A three-button remote with an integrated microphone provides control over music playback, video controls, and call management.",
        vendor: "B",
        addInfo: 
          `Noise Control: None 
          Headphone Jack: 3.5mm 
          Model Name: Earphones 1 
          Item Weight: 30grams 
          Net Quantity: 1 
          Product Dimensions: 3.6 x 3.6 x 2.2 cm`,
        discount: 22,
      },
      {
        id: 20,
        name: "Red Apple",
        category: "Vegetables & Fruits",
        quantity: 24,
        price: 99,
        image: "apple.png",
        images: ["apple.png", "barcode.avif", "fssai.jpg"],
        ratingP: 4.6,
        description:
          " It is a nutritious choice, rich in fiber, vitamin C, and antioxidants, which can contribute to a healthy diet and may help lower cholesterol and blood sugar. Apples can be eaten raw for a crisp snack or used in cooking for dishes like pies and sauces.",
        vendor: "Daily Fresh Farms, Harayana",
      },
      {
        id: 21,
        name: "Green Tea",
        category: "Coffee & Tea",
        quantity: 9,
        price: 199,
        image: "greentea.jpg",
        images: ["greentea.jpg", "barcode.avif", "fssai.jpg"],
        ratingP: 4.0,
        description:
          "A green tea product description should highlight its origin (leaves from Camellia sinensis), minimal processing (not oxidized), and flavor profile (grassy, earthy, vegetal, or floral).",
        vendor: "Tea Valley, Assam",
      },
    ]);

    console.log("Database seeded with updated information.");
  } catch (error) {
    console.log("Error seeding database", error);
  } finally {
    mongoose.connection.close();
  }
});
